version: '2'
services:
  app1:
    build: .
    depends_on:
      - db
    environment:
      - REDIS_HOST=db
      - REDIS_PORT=6379
  app2:
    build: .
    depends_on:
      - db
    environment:
      - REDIS_HOST=db
      - REDIS_PORT=6379
  app3:
    build: .
    depends_on:
      - db
    environment:
      - REDIS_HOST=db
      - REDIS_PORT=6379
  db:
    image: redis
    ports:
        - "6379"
  nginx:
    build: ./lb
    links:
        - app1:app1
        - app2:app2
        - app3:app3
    ports:
        - "8686:80" 
